# Generated by Django 5.1.7 on 2025-03-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('imgage', models.ImageField(blank=True, null=True, upload_to='webimage/')),
                ('address1', models.CharField(max_length=255)),
                ('number1', models.CharField(max_length=10)),
                ('number2', models.CharField(blank=True, max_length=10, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
