# Generated by Django 5.1.7 on 2025-03-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websitesettings',
            old_name='imgage',
            new_name='image',
        ),
    ]
