# Generated by Django 5.1.7 on 2025-04-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0005_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
