# Generated by Django 5.1.7 on 2025-04-05 11:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0006_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrandingProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('keyfeature1', models.CharField(max_length=500)),
                ('keyfeature2', models.CharField(blank=True, max_length=500, null=True)),
                ('keyfeature3', models.CharField(blank=True, max_length=500, null=True)),
                ('keyfeature4', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='product/pdf/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
