# Generated by Django 5.1.7 on 2025-04-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0007_trandingproducts_product_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trandingproducts',
            name='image',
            field=models.ImageField(default=1, upload_to='TrandingProduct/'),
            preserve_default=False,
        ),
    ]
