# Generated by Django 5.1.7 on 2025-04-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0008_trandingproducts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='street_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='zipcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trandingproducts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
