# Generated by Django 5.1.7 on 2025-04-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0009_alter_contactus_city_alter_contactus_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=500)),
                ('Full_address', models.CharField(max_length=600)),
                ('zip_code', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('product_type', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('needed_by', models.DateField(blank=True, null=True)),
                ('project_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
