# Generated by Django 5.1.7 on 2025-04-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0010_contactinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tag_line',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
