# Generated by Django 5.1.7 on 2025-04-28 10:12

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0012_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tag_line',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RentAndHireProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='product/pdf/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentproducts', to='customadmin.category')),
            ],
        ),
        migrations.CreateModel(
            name='RentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rent_and_hire_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentimages', to='customadmin.rentandhireproduct')),
            ],
        ),
    ]
