# Generated by Django 5.1.7 on 2025-04-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0013_alter_category_tag_line_rentandhireproduct_rentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentandhireproduct',
            name='tag_line1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentandhireproduct',
            name='tag_line2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentandhireproduct',
            name='tag_line3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
