# Generated by Django 3.0 on 2022-08-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_forgetpassmailverify'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='category',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
