# Generated by Django 3.0 on 2022-09-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='strpass',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
