# Generated by Django 3.0 on 2022-09-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usernumberverify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernumberverify',
            name='user',
        ),
        migrations.AddField(
            model_name='usernumberverify',
            name='number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
