# Generated by Django 3.0 on 2022-09-07 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220907_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernumberverify',
            name='number',
        ),
        migrations.AddField(
            model_name='usernumberverify',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
