# Generated by Django 5.0.6 on 2024-05-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_is_company_customuser_is_landload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('watting', 'Watting'), ('approved', 'Approved'), ('regected', 'Regected')], default='watting', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('T', 'tenat'), ('L', 'Landload')], max_length=255, null=True),
        ),
    ]
