# Generated by Django 5.1.7 on 2025-03-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_address_customuser_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_landload',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='delete_status',
            field=models.BooleanField(default=0),
        ),
    ]
