# Generated by Django 5.1.7 on 2025-03-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_customuser_is_landload_remove_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='designation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='salary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
